// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using move.data;

#nullable disable

namespace move.Migrations
{
    [DbContext(typeof(ApplicationDBcontext))]
    [Migration("20250203164026_addcateguryandmooovemodels")]
    partial class addcateguryandmooovemodels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("move.Models.categury", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("categuryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("categuries");
                });

            modelBuilder.Entity("move.Models.mooove", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("categuryId")
                        .HasColumnType("int");

                    b.Property<int>("date")
                        .HasColumnType("int");

                    b.Property<string>("img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("moooveId")
                        .HasColumnType("int");

                    b.Property<int>("time")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("moooveId");

                    b.ToTable("Moooves");
                });

            modelBuilder.Entity("move.Models.mooove", b =>
                {
                    b.HasOne("move.Models.mooove", null)
                        .WithMany("categuries")
                        .HasForeignKey("moooveId");
                });

            modelBuilder.Entity("move.Models.mooove", b =>
                {
                    b.Navigation("categuries");
                });
#pragma warning restore 612, 618
        }
    }
}
